### PR TITLE
Fix CT and internals (a bit)

### LINKED ISSUE #50: fun_info vs stacktrace differences make tests fail in OTP 26
#### The bug

Tests fail on OTP 26.

The reason is that we're using internal definitions to compare stuff and then this happens, in `nuntius_mocker:run_expects/2`:

```
{stmfa,{nuntius_api_SUITE,'-expect_message/1-inlined-0-',1}}
=/=
{fimfa,{nuntius_api_SUITE,'-expect_message/1-fun-0-',1}}
```

Since our CI workflows cover OTP 23 and 24, and this is not apparent, I'm convinced (and I kinda remember something for OTP 25/26 about inlining) this change took place later than when we coded `nuntius` initially

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Erlang/OTP: 26.0.1
* `nuntius`: 0.0.3

#### How to replicate

An ordered list of steps to replicate the bug:

1. run `rebar3 ct`
2. search for `{badmatch,{error,not_mocked}` in the error output
3. look at file `nuntius_mocker`, lines 110-112

#### Expected behaviour

Don't crash.

#### Additional context

Not applicable.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #50.

### CODE REVIEW

File: src/nuntius_mocker.erl [hunk 1]
```diff
@@ -118,15 +118,20 @@ run_expects(Message, Expects) ->
...
+    F = coerce_fun(F0),
     {arity, A} = erlang:fun_info(Expect, arity),
     {M, F, A}.
 
 mfa_from_stacktrace(Stacktrace) ->
-    [{M, F, Args, _} | _] = Stacktrace,
+    [{M, F0, Args, _} | _] = Stacktrace,
     A = length(Args),
+    F = coerce_fun(F0),
     {M, F, A}.
```
Comment (paulo-ferraz-oliveira) [inline src/nuntius_mocker.erl:130]: Not sure if we know of a better, more modern way of doing this, actually. It's served our purposes until now 😄

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, would you know why [this](https://github.com/2Latinos/nuntius/actions/runs/5404228192/jobs/9818123907?pr=51#step:7:1) is happening?

`rebar3_format` is seemingly [OTP 25 -ready](https://github.com/AdRoll/rebar3_format/blob/main/.github/workflows/erlang.yml#L16).

**Comment by paulo-ferraz-oliveira** [comment]
I also get this result locally, with Erlang 25.2, even if I `rm -rf ~/.cache/rebar/hex`.

**Comment by paulo-ferraz-oliveira** [comment]
Smells like some plugin clashing. (or, worst case, but doubt it, there's an issue with `rebar3` dependency calculations)

**Comment by paulo-ferraz-oliveira** [comment]
Hm... I see `katana_code` forces `{feature, maybe_expr, enable}` by default.

The latest code wasn't released: https://github.com/inaka/katana-code/compare/2.0.1...main

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna try `{overrides, [{override, [{erl_opts, []}]}]}.` to see what happens in CI.

In any case, `elvis_core` seems to "suffer" from the same issue, regarding the use of the aforementioned `erlc_opt`.

**Comment by elbrujohalcon** [comment]
If you know how, please do send a PR on katana_code and elvis_core to fix the issues.

File: src/nuntius_mocker.erl (hunk 1 above)
Comment (elbrujohalcon) [reply src/nuntius_mocker.erl:130]: I'm a little bit skeptical of coercing the fun name in `mfa_from_fun_info/1` since we do want to match only against the specific expectation function head there… not any of its internal ones… nor any external one. I guess tests were failing in OTP26 and that triggered this adjustments, right?

**Review by elbrujohalcon — CHANGES_REQUESTED** [review]

File: rebar.config [hunk 2]
```diff
@@ -1,14 +1,16 @@
...
-{minimum_otp_vsn, "23"}.
+{minimum_otp_vsn, "24"}.
 
 {cover_enabled, true}.
 
 {cover_opts, [verbose]}.
 
 {deps, []}.
 
+{overrides, [{override, [{erl_opts, []}]}]}.
```
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply rebar.config:12]: I mean, maybe (?) For the dependencies I didn't test how e.g. not having "warnings as errors" this would work, but I can make them the same, and check the results. Thanks, @elbrujohalcon. Will do that.

**Comment by paulo-ferraz-oliveira** [comment]
I will look into traversing the stack trace. It felt like "magic" and "hacky" to us, at the time, but we were more time-bound, I guess, and now can improve on it. Thanks.

File: src/nuntius_mocker.erl (hunk 1 above)
Comment (paulo-ferraz-oliveira) [reply src/nuntius_mocker.erl:130]: Correct. A function head that should not throw will look like

```erlang
[
{nuntius_api_SUITE,'-expect_message/1-inlined-0-',[unknown],[
  {file,"nuntius/test/nuntius_api_SUITE.erl"},{line,206}
]},
{nuntius_mocker,'-run_expects/2-fun-0-',4,[
  {file,"nuntius/src/nuntius_mocker.erl"},{line,105}
]},
{maps,fold_1,3,[
  {file,"maps.erl"},{line,411}
]},
{nuntius_mocker,handle_message,2,[
  {file,"nuntius/src/nuntius_mocker.erl"},{line,97}
]},
{nuntius_mocker,loop,1,[
  {file,"nuntius/src/nuntius_mocker.erl"},{line,71}
]},
{proc_lib,init_p_do_apply,3,[
  {file,"proc_lib.erl"},{line,240}
]}
]
```

where StMFA is

```erlang
{nuntius_api_SUITE,'-expect_message/1-inlined-0-',1}
```

and FiMFA is

```erlang
{nuntius_api_SUITE,'-expect_message/1-fun-0-',1}
```

meaning the call is in `nuntius_api_SUITE:206` where we're aiming for a call no expect is able to handle.

Comment (paulo-ferraz-oliveira) [reply src/nuntius_mocker.erl:130]: > I doubt that OTP provides a way of determining if some function "is written" inside another one

At the time we created this, I don't think it did. And this was something I actually discussed with @eproxus and a hint for the solution was born from that discussion.

Comment (paulo-ferraz-oliveira) [reply src/nuntius_mocker.erl:130]: I'm trying to improve this, but:

* should throw is
```erlang
[
{lists,sort,[fff],[]},
{nuntius_mocker,'-run_expects/2-fun-0-',4,[]},
{maps,fold_1,3,[]},
{nuntius_mocker,handle_message,2,[]},
{nuntius_mocker,loop,1,[]},
{proc_lib,init_p_do_apply,3,[]}
]
```
* should not throw is
```
{st,[
{nuntius_api_SUITE,'-expect_message/1-inlined-0-',[unknown],[]},
{nuntius_mocker,'-run_expects/2-fun-0-',4,[]},
{maps,fold_1,3,[]},
{nuntius_mocker,handle_message,2,[]},
{nuntius_mocker,loop,1,[]},
{proc_lib,init_p_do_apply,3,[]}
]}
```

so I'm out of ideas on what to search (the head does contain the information we're looking for, though, since we're just matching the exception on function clauses - don't know if you saw/remember that bit)

**Comment by paulo-ferraz-oliveira** [comment]
> If you know how, please do send a PR on katana_code and elvis_core to fix the issues.

I think `katana_code` is fixed in `main`, but not released.
`elvis_core` doesn't seem fixed, but it's probably not breaking CI because of https://github.com/inaka/elvis_core/blob/main/.github/workflows/ci.yml#L45.

**Comment by paulo-ferraz-oliveira** [comment]
What rework shall we do here? Would it be Ok to have a "default" expect which would run after all the others (i.e. none other was matched) and it would either throw or output a log stating "no match"? This seems like a "nice compromise" for what we state as goals.

**Comment by elbrujohalcon** [comment]
> What rework shall we do here? Would it be Ok to have a "default" expect which would run after all the others (i.e. none other was matched) and it would either throw or output a log stating "no match"? This seems like a "nice compromise" for what we state as goals.

Yeah... that sounds like a good idea.

File: README.md [hunk 3]
```diff
@@ -54,6 +54,15 @@ the message,
...
 the mocked process.
 
+## Expectation handling
+
+If, when `nuntius` executes your expectations, none matches the input (which means it's better
+to have a catch-all) it'll exit with `{nuntius, nomatch, StackTrace}`. This can be prevented by
+using option `exit_on_nomatch` as `false` (the default is to exit).
+
+On the other hand, if an exception occurs inside one of your expectations, `nuntius` will
+also exit with `{nuntius, nomatch, StackTrace}` so you can analyze what needs to be fixed.
```
Comment (paulo-ferraz-oliveira) [inline README.md:64]: This is new!

Comment (paulo-ferraz-oliveira) [reply README.md:64]: And code/tests were implemented to support the claims...

File: src/nuntius_mocker.erl (hunk 1 above)
Comment (paulo-ferraz-oliveira) [reply src/nuntius_mocker.erl]: Resolve'ing for readability. This is dealt with further, as per discussion.

**Review by elbrujohalcon — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Great stuff. I'll want to advance some more on `nuntiux`, then get back to this one, solve a few issues (potentially all) and we can then release 1.0.0 👍
